# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jacu < Formula
  desc "Governance harness for coding agents"
  homepage "https://github.com/jacu-dev/jacu-harness"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacu-dev/jacu-harness/releases/download/v0.3.0/jacu_0.3.0_darwin_amd64.tar.gz"
      sha256 "f73ddf2e6de6117966d92258b5d04f2e7962d37becf238d0ddf57ca4b7f54676"

      define_method(:install) do
        bin.install "jacu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacu-dev/jacu-harness/releases/download/v0.3.0/jacu_0.3.0_darwin_arm64.tar.gz"
      sha256 "c004ae0f42cb3a832774722050cd2a8c9eb168572cd2c09be5f095f48d1866a6"

      define_method(:install) do
        bin.install "jacu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacu-dev/jacu-harness/releases/download/v0.3.0/jacu_0.3.0_linux_amd64.tar.gz"
      sha256 "625d58d0f80ef97e58614fb6949f6c2ded02eacc33021d05f54cf9a0403293f9"
      define_method(:install) do
        bin.install "jacu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacu-dev/jacu-harness/releases/download/v0.3.0/jacu_0.3.0_linux_arm64.tar.gz"
      sha256 "11f1e06fb0474820d1a3476631be255e79730aca90438ca7edb09f6e067f5cef"
      define_method(:install) do
        bin.install "jacu"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jacu version")
  end
end
